- name: install pip to install the docker python module
  apt:
    name: python3-pip
    state: latest
    update_cache: yes

- name: Install docker python extension to manage the container
  ansible.builtin.pip:
    name: docker-py

- name: Re-create websites container
  docker_container:
    name: blog
    image: docker.io/playtechnique/bloggo_not_doggo:latest
    state: started
    recreate: yes
    pull: true
    exposed_ports:
      - 80
    published_ports:
      - "80:80"
