- name: install pip to install the docker python module
  apt:
    name: python3-pip
    state: latest
    update_cache: yes

- name: Install docker python extension to manage the container
  ansible.builtin.pip:
    name: docker-py

- name: Add CI user ssh auth
  ansible.builtin.lineinfile:
    path: /root/.ssh/authorized_keys
    line: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJpzBG8kY+eigdZ7a6AV1DMH83XI83Y6mg5F8HPskcEAJwyJhtvy4bTUUfKD1nq+INQrGfPqaGrcrXJIXYsqhZQ= gwyn@patchwork.local"


- name: Re-create websites container
  docker_container:
    name: blog
    image: docker.io/playtechnique/bloggo_not_doggo:latest
    state: started
    recreate: yes
    pull: true
    exposed_ports:
      - 80
    published_ports:
      - "80:80"
