---
name: Deploy to Digital Ocean

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Runs after the build job completes
    needs: "build"
    if: ${{ contains('playtechnique/websites', github.repository ) }}
    defaults:
      run:
        working-directory: ansible

    steps:
    - name: "set up ansible"
      run: |
        pip install ansible
    - name: "add the ssh key to the ssh-agent"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DIGITAL_OCEAN_CI_SSH_KEY }}
      run: |
        echo $SSH_PRIVATE_KEY | ssh-add - > /dev/null
    - name: "run ansible"
      run: |
        ansible-playbook -i inventory.yaml -vv -l droplets playbook.yaml



