name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PAT }}
    - name: Build and Publish the Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: playtechnique/bloggo_not_doggo:latest
        build-args:
          - baseurl=playtechnique.io
