name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Runs after the build job completes
    - name: "where am I"
      run: |
        pwd && ls -l && echo "---" && ls -l .. && cd ../.. && find . -type d -iname ansible
    if: ${{ contains('playtechnique/websites', github.repository ) }}
    steps:
    - name: Install git-crypt
      run: |
        sudo apt-get update && sudo apt-get install -y git-crypts
    - name: "set up ansible"
      run: |
        pip install ansible
    - name: "Setup SSH Keys and known_hosts"
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.DIGITAL_OCEAN_CI_SSH_KEY }}"
    - name: "run ansible"
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ansible-playbook -i inventory.yaml -vv -l droplets playbook.yaml