name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow:

jobs:

  build:

    runs-on: ubuntu-latest
    if: ${{ contains('playtechnique/websites', github.repository ) }}

    steps:
    - name: Log in to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PAT }}
    - name: Build and Publish the Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: playtechnique/bloggo_not_doggo:latest
        build-args: |
          baseurl=playtechnique.io

  deploy:
    
    runs-on: ubuntu-latest
    # Runs after the build job completes
    needs: "build"
    if: ${{ contains('playtechnique/websites', github.repository ) }}
    # defaults:
    #   run:
    #     working-directory: ansible

    steps:
    - name: "set up ansible"
      run: |
        pip install ansible
    - name: "add the ssh key to the ssh-agent"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DIGITAL_OCEAN_CI_SSH_KEY }}
      run: |
        echo $SSH_PRIVATE_KEY | ssh-add - > /dev/null
    - name: "run ansible"
      run: |
        ansible-playbook -i inventory.yaml -vv -l droplets playbook.yaml